config/routes.rb
Rails.application.routes.draw do
  resources :new_products
  root to:'new_products#index'
  devise_for :admins
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/new.rb
class New < ApplicationRecord
    has_one_attached :featured_image
    has_rich_text :content
end

app/models/new_product.rb
class NewProduct < ApplicationRecord
    has_one_attached :featured_image
    has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_admin!, except: :index
end

app/controllers/new_products_controller.rb
class NewProductsController < ApplicationController
  before_action :set_new_product, only: %i[ show edit update destroy ]

  # GET /new_products or /new_products.json
  def index
    @new_products = NewProduct.all
  end

  # GET /new_products/1 or /new_products/1.json
  def show
  end

  # GET /new_products/new
  def new
    @new_product = NewProduct.new
  end

  # GET /new_products/1/edit
  def edit
  end

  # POST /new_products or /new_products.json
  def create
    @new_product = NewProduct.new(new_product_params)

    respond_to do |format|
      if @new_product.save
        format.html { redirect_to @new_product, notice: "New product was successfully created." }
        format.json { render :show, status: :created, location: @new_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @new_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /new_products/1 or /new_products/1.json
  def update
    respond_to do |format|
      if @new_product.update(new_product_params)
        format.html { redirect_to @new_product, notice: "New product was successfully updated." }
        format.json { render :show, status: :ok, location: @new_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @new_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /new_products/1 or /new_products/1.json
  def destroy
    @new_product.destroy
    respond_to do |format|
      format.html { redirect_to new_products_url, notice: "New product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_new_product
      @new_product = NewProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def new_product_params
      params.require(:new_product).permit(:title, :author, :featured_image, :content)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [ :show, :edit, :update, :destroy, :create ]

  # GET /news or /news.json
  def index
    @news = New.all
  end

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @new = New.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @new = New.new(new_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: "New was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: "New was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_url, notice: "New was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @new = New.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def new_params
      params.require(:new).permit(:title, :author, :featured_image, :content, :new_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_products_helper.rb
module NewProductsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chichila Kawaii Rações Gourmet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <div class='row'>
        <%= yield %>
      </div>
    </div>
    <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Desenvolvido</strong> by <a href="https://www.linkedin.com/in/denner-viana-11b62939/">Denner viana</a>.-
       <a href="https://github.com/dennerruby">My Git Hub</a>.
      </p>
    </div>
  </footer>
  </body>
</html>

app/views/new_products/_form.html.erb
<%= form_with(model: new_product, local: true) do |form| %>
  <% if new_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(new_product.errors.count, "error") %> prohibited this new_product from being saved:</h2>

      <ul>
        <% new_product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="file">
  <label class="file-label">
    <%= form.file_field :featured_image, class: 'file-input' %>
    <span class="file-cta">
      <span class="file-icon">
        <i class="fas fa-upload"></i>
      </span>
      <span class="file-label">
        Escolha a imagem de destaque…
      </span>
    </span>
  </label>
</div>

</br>

<div class="field">
  <%= form.label 'Título', class: 'label' %>
  <div class="control">
    <%= form.text_field :title, class: 'input' %>
  </div>
</div>

<div class="field">
  <%= form.label 'Autor', class: 'label' %>
  <div class="control">
    <%= form.text_field :author, class: 'input' %>
  </div>
</div>


<div class="field">
  <%= form.label 'Conteúdo', class: 'label' %>
  <%= form.rich_text_area :content %>
</div>

<div class="field is-grouped">
  <div class="control">
  <%= form.submit 'Criar', class: 'button is-link' %>
  </div>
  <div class="control">
    <%= link_to 'Voltar',  href="/", class: 'button is-link is-light' %>
  </div>
</div>


<% end %>

app/views/new_products/edit.html.erb
<h1>Editing New Product</h1>

<%= render 'form', new_product: @new_product %>

<%= link_to 'Show', @new_product %> |
<%= link_to 'Back', new_products_path %>

app/views/new_products/index.html.erb
</br></br>
<h1 class="title">Produtos</h1>
</br>
 

<% @new_products.each do |new_product| %>
  <div class="columns">
    <div class="column is-four-fifths">
    <div class="card">
    <div class="card-image">
      <figure class="image is-full is-marginless is-4by3">
        <%= image_tag new_product.featured_image %>
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <a href="<%= new_product_path(id: new_product.id) %>"><p class="title is-4"><%= new_product.author %></p></a>
        </div>
      </div>
      <p>Autor: <%= new_product.author %> - <%= new_product.created_at.strftime("%d/%m/%Y") %></p>
    </div>
  </div>

    </div>
  </div>
<% end %>

app/views/new_products/new.html.erb
</br></br> <h1 class="title is-1">Publicar Novo Produto</h1> 

<%= render 'form', new_product: @new_product %>

app/views/new_products/show.html.erb
</br></br>
<figure class="image is-3by1">
  <%= image_tag @new_product.featured_image%>
</figure></br>
<div class="columns">
  <div class="column"><p class="title"><%= @new_product.title %></p>
</div>
</div></br></br>
<div class="columns">
  <div class="column is-three-quarters"><%= @new_product.content %></div>
</div>

app/views/news/_form.html.erb
<%= form_with(model: new, local: true) do |form| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(new.errors.count, "error") %> prohibited this new from being saved:</h2>
 
      <ul>
        <% new.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="file">
    <label class="file-label">
      <%= form.file_field :featured_image, class: 'file-input' %>
      <span class="file-cta">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          Escolha a imagem de destaque…
        </span>
      </span>
    </label>
  </div>
 
  </br>
 
  <div class="field">
    <%= form.label 'Título', class: 'label' %>
    <div class="control">
      <%= form.text_field :title, class: 'input' %>
    </div>
  </div>
 
  <div class="field">
    <%= form.label 'Autor', class: 'label' %>
    <div class="control">
      <%= form.text_field :author, class: 'input' %>
    </div>
  </div>
 
 
  <div class="field">
    <%= form.label 'Conteúdo', class: 'label' %>
    <%= form.rich_text_area :content %>
  </div>
 
  <div class="field is-grouped">
    <div class="control">
    <%= form.submit 'Criar', class: 'button is-link' %>
    </div>
    <div class="control">
      <%= link_to 'Voltar',  href="/", class: 'button is-link is-light' %>
    </div>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_path %>

app/views/news/index.html.erb
</br></br>
<h1 class="title">Produtos</h1>
</br>
 
<% @news.each do |new| %>
  <div class="columns">
    <div class="column is-four-fifths">
    <div class="card">
    <div class="card-image">
      <figure class="image is-full is-marginless is-3by1">
        <%= image_tag new.featured_image %>
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <a href="<%= new_path(id: new.id) %>"><p class="title is-4"><%= new.author %></p></a>
        </div>
      </div>
      <p>Autor: <%= new.author %> - <%= new.created_at.strftime("%d/%m/%Y") %></p>
    </div>
  </div>

    </div>
  </div>
<% end %>

app/views/news/new.html.erb
</br></br> <h1 class="title is-1">Publicar Novo Produto</h1> 
 
<%= render 'form', new: @new %>

app/views/news/show.html.erb
</br></br>
<figure class="image is-3by1">
  <%= image_tag @new.featured_image%>
</figure></br>
<div class="columns">
  <div class="column"><p class="title"><%= @new.title %></p>
</div>
</div></br></br>
<div class="columns">
  <div class="column is-three-quarters"><%= @new.content %></div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar is-success" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src="https://i.ibb.co/G0csqMQ/logo-bg-escuro-400.png" width="112" height='28'>
      </a>
 
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
 
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href='/new_products/new'>
          + Cadastrar Novo Produto
        </a>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% unless admin_signed_in? %>
              <a class="button is-primary" href='/admins/sign_up'>
                <strong>Cadastre-se</strong>
              </a>
              <a class="button is-light" href='/admins/sign_in'>
                Entrar
              </a>
            <% end %>  
            <% if admin_signed_in? %>
              <%= link_to "Sair", destroy_admin_session_path, method: :delete, class: 'button is-light'  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>